### ISSUE TITLE
Close vsnetrw tab when opening a file

### ISSUE THREAD

**Issue by carlosedp** [danprince/vsnetrw#10]
When a file is chosen to be open, it would be nice to have the vsnetrw file tab to be closed.

Also it would be great to have an option to close the tab without open anything with ESC for example.

**Comment by danprince** [comment]
Seems reasonable. I don't use tabs in vscode, so never noticed it hanging around.

Tried to hit both requests with a new version. The vsnetrw editor tab should close after opening/creating a file and there's a new `vsnetrw.close` command that will close the editor manually (bound to `esc` by default).

Should be live in the marketplace in a few mins, or you can grab the VSIX from the release directly: https://github.com/danprince/vsnetrw/releases/tag/v0.2.4

**Comment by carlosedp** [comment]
Awesome!
