### ISSUE TITLE
Could you please implement bookmarks?

### ISSUE THREAD

**Issue by ishovkun** [danprince/vsnetrw#12]
Something like ranger, nnn, and others can do?
Ideally, I would save a location into a registed, and then I should be able to jump to this location by referring to that register (like vim bookmarks).

**Comment by danprince** [comment]
Hi @ishovkun, can you explain in a little more detail how you see this working?

I don't use any of the tools that offer this functionality and it's a little unclear to me what it involves.

You would open a directory in a vsnetrw buffer, then press a keyboard shortcut to save that directory to a register? Then in future, an alternate keyboard shortcut would re-open that directory in vsnetrw?

**Comment by ishovkun** [comment]
The way it works in vim (or emacs ranger if you prefer a file manager example):
- the user navigates to a directory
- the user hits a two-fold keybinding, e.g. `ma`:
     - the first letter `m` designates that the user wants to save the current path
     - the second symbol `a` designates the register to store the path at. The user could use any other alphanumeric character instead of `a`.
- When the user wants to use a location previously saved in register `t`, he would issue `'t`:
     - the first character `'` indicates that the user wants to go to a saved location
     - the second character `t` indicates the register that stores the path.
    
I would say that these bookmarks should be global as opposed to being workspace-based.

Cheers

**Comment by ishovkun** [comment]
One note that I would like to add is when the user jumps to a path, vsnetrw should jump to a directory as opposed to a specific file.

Personally, I work a mathematical modeling software takes an input file, crunches the numbers, and writes the output. The source code of the applications, the input files, and the output files typically reside in different places on my filesystem. 

I have a designated directory, where my input files are stored according to the projects they pertain, e.g.:
```
~/simulations/finite_elements/10-fractures/config.yaml
~/simulations/finite_elements/geos/config.yaml
~/simulations/stanford/hybdrid/config.yaml
```
There is a lot of sub-directories in this structure, and it is tedious to navigate within a long path. Sometimes, I need to jump to the `~/Downloads` directory to copy/move an file that I downloaded into a destination. 

There is no reason for me to store these input files along with the source code, so the VS-code's built-in file searcher would not cut it for this use case.

Please, let me know if you need further clarifications.

**Comment by danprince** [comment]
@ishovkun How does this look in terms of UX?

https://github.com/danprince/vsnetrw/assets/1266011/b69eadd2-d6b4-4c62-83e5-8adfeeb9f829

I don't _really_ want to maintain features that aren't in the original netrw, as this extension isn't supposed to be a general purpose file manager.

However, I've checked these changes into a `bookmarks` branch. Here's a VSIX file if you want to use the extension with these changes.

[vsnetrw-0.2.5-bookmarks.vsix.zip](https://github.com/danprince/vsnetrw/files/12431670/vsnetrw-0.2.5-bookmarks.vsix.zip)

**Comment by ishovkun** [comment]
This is awesome! Thank you so much!!!!
