### ISSUE TITLE
Line numbers flashing when opening new directories

### ISSUE THREAD

**Issue by lwieckowski** [danprince/vsnetrw#20]
When opening a directory that hasn't been opened yet, the line numbers flash for a very brief moment:

https://github.com/danprince/vsnetrw/assets/24639666/48b14403-bb1d-4369-b958-ec9db9f1b87f

I've tested this on two machines (Windows and Mac). Also, using a clean config and disabling all other extensions does not change this behaviour.

Is that something others experience too?

**Comment by danprince** [comment]
Hey @lwieckowski 👋! Taking a look at this now.

I have line numbers disabled globally across vscode, so I'm afraid I wouldn't ever have caught this in development.

I can't explicitly remember doing anything specific to turn line numbers off as part of the extension, but it seems like I did add that to the package specific configuration here.

https://github.com/danprince/vsnetrw/blob/834599075a035c63f0a2e3416d4389200052908a/package.json#L111

Given that they appear then disappear, I wonder if vscode is reloading the package level config each time?

A quick test could be to add the following to your own `settings.json` and see whether that prevents the flashing?

```json5
"[vsnetrw]": {
  "editor.lineNumbers": "off"
}
```

It could also be the case that the extension mode isn't set initially, which causes the flash? In that case, I'm not sure what the workaround would be. It seems a little bit odd that there would be any time window where `editor.lineNumbers` was not `"off"`.

If you get any more clues, do shout and I can look at what the fix might be.

**Comment by lwieckowski** [comment]
Hey @danprince, thanks for looking into it so quickly. Unfortunately, explicitly setting line numbers to off for `vsnetrw` in `settings.json`did not help. It seems these settings are set by default anyway (vscode suggested autocomplete).

It seems that vscode loads extension specific settings after the document has been loaded with the global settings.

What seems to work is to set line numbers to off globally, and then enable them for specific file types. I think this is good enough for me, there are not that many.

BTW, I love the extension, exactly what I've been looking for after not being able to use vim at work. Great job 👍

**Comment by danprince** [comment]
> BTW, I love the extension, exactly what I've been looking for after not being able to use vim at work. Great job 👍

🥳

Thanks for investigating! The plain text discovery was a great clue. It turns out the extension was setting the language type _after_ showing the document. The order should be correct now.

https://github.com/danprince/vsnetrw/blob/e5b59666400b1156729a7a54f2024c9350c1f159/extension.js#L118-L122

I've published that change in `v0.3.2`, so feel free to try it out and see if it fixes that problem without a need for the workaround.

**Comment by lwieckowski** [comment]
I can confirm it works now. Thanks for fixing this so quickly!
